CREATE TABLE REZERWACJE_LOG (
    ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    ID_REZERWACJI INT,
    DATA DATE,
    STATUS CHAR(1),
    CONSTRAINT REZERWACJE_LOG_PK PRIMARY KEY (
        ID
    )
    ENABLE
);

ALTER TABLE REZERWACJE_LOG
ADD CONSTRAINT REZERWACJE_LOG_FK1 FOREIGN KEY (
    ID_REZERWACJI
)
REFERENCES REZERWACJE (
    NR_REZERWACJI
)
ENABLE;