CREATE OR REPLACE TRIGGER WpisNowejRezerwacji
    AFTER INSERT ON REZERWACJE
    FOR EACH ROW
    BEGIN
        INSERT INTO REZERWACJE_LOG(ID_REZERWACJI, DATA, STATUS)
        VALUES (:NEW.NR_REZERWACJI, CURRENT_DATE, 'N');
    END;

CREATE OR REPLACE TRIGGER WpisAktualizacjiRezerwacji
    AFTER UPDATE ON REZERWACJE
    FOR EACH ROW
    BEGIN
        INSERT INTO REZERWACJE_LOG(ID_REZERWACJI, DATA, STATUS)
        VALUES (:NEW.NR_REZERWACJI, CURRENT_DATE, :NEW.STATUS);
    END;

CREATE OR REPLACE TRIGGER ZabronUsuwaniaRezerwacji
    BEFORE DELETE ON REZERWACJE
    FOR EACH ROW
    BEGIN
        RAISE_APPLICATION_ERROR(-20999, 'Usuwanie rezerwacji jest zabronione');
    END;

