ALTER TABLE WYCIECZKI
    ADD LICZBA_WOLNYCH_MIEJSC INT;

CREATE OR REPLACE PROCEDURE przelicz
AS
    BEGIN
        UPDATE WYCIECZKI W
            SET W.LICZBA_WOLNYCH_MIEJSC = (
                SELECT W.LICZBA_MIEJSC - COUNT(*)
                FROM REZERWACJE R
                    WHERE (R.STATUS <> 'A') AND (W.ID_WYCIECZKI = R.ID_WYCIECZKI)
            );

        COMMIT;
    END;